---

pipelineConfig:
  baseFolder: "INFRA/ansible"
  yamlProjectConfigList:
#    - pipelineConfigYaml: "config.ansible.aap.yml"
    - pipelineConfigYaml: "config.ansible.linux.yml"
#    - pipelineConfigYaml: "config.ansible.windows.yml"
