---

pipelineConfig:
  baseFolder: "INFRA/vm-templates"
  repoUrl: "git@bitbucket.org:lj020326/packer-templates.git"
  mirrorRepoDir: "/var/jenkins_home/git_repo_references/vm-templates/vm-templates.git"
  gitCredentialsId: "bitbucket-ssh-jenkins"
  vmTemplateList:
    - build_distribution: CentOS'
      build_release: '9'
    - build_distribution: CentOS'
      build_release: '8-stream'
    - build_distribution: CentOS'
      build_release: '8'
    - build_distribution: CentOS'
      build_release: '7'
    - build_distribution: Debian'
      build_release: '10'
    - build_distribution: Debian'
      build_release: '9'
    - build_distribution: RedHat'
      build_release: '9'
    - build_distribution: RedHat'
      build_release: '8'
    - build_distribution: RedHat'
      build_release: '7'
    - build_distribution: Ubuntu'
      build_release: '22.04'
    - build_distribution: Ubuntu'
      build_release: '20.04'
    - build_distribution: Ubuntu'
      build_release: '18.04'
    - build_distribution: Windows'
      build_release: '2019'
    - build_distribution: Windows'
      build_release: '2016'
    - build_distribution: Windows'
      build_release: '2012r2'
