#!/usr/bin/env groovy

import com.dettonville.pipeline.utils.JsonUtils
import com.dettonville.pipeline.utils.MapMerge
import com.dettonville.pipeline.utils.Utilities
import com.dettonville.pipeline.utils.logging.Logger

import groovy.transform.Field
@Field Logger log = new Logger(this)

def call(Map params = [:]) {

    Map config = loadPipelineConfig(params)

    pipeline {
        agent {
            docker {
                label config.jenkinsNodeLabel
                image config.runnerImage
                args config.runnerArgs
                reuseNode true
                alwaysPull true
            }
        }
        options {
            disableConcurrentBuilds()
            timestamps()
            buildDiscarder(logRotator(numToKeepStr: '10'))
            skipDefaultCheckout(config.skipDefaultCheckout)
            timeout(time: config.timeout, unit: config.timeoutUnit)
        }
        stages {
            stage('Indexer Execution') {
                when {
                    branch 'main'
                }
                stages {
                    stage('Check Skip') {
                        steps {
                            scmSkip(skipPattern: '.*\\[(ci skip|skip ci)\\].*')
                        }
                    }

                    stage('Indexer: Setup Directory') {
                        steps {
                            script {
                                log.info("Starting code indexer pipeline for ${env.JOB_NAME}")
                                config = loadGiteaConfigs(config)
                                sh "mkdir -p ${config.indexDir}"
                            }
                        }
                    }

                    stage('Indexer: Build Universal Ctags') {
                        steps {
                            script {
                                log.info("Ctags version info")
                                sh "ctags --version"

                                log.info("Generating Universal Ctags index...")
//                                 sh "ctags -R -f ${config.indexDir}/tags . || true"
                                if (fileExists(".ctags.d/project.ctags")) {
                                    sh "ctags --options=.ctags.d/project.ctags -R -f ${config.indexDir}/tags . || true"
                                } else {
                                    sh "ctags -R -f ${config.indexDir}/tags . || true"
                                }
                            }
                        }
                    }

                    stage('Indexer: Build tgrep Index') {
                        steps {
                            script {
                                log.info("tgrep version info")
                                sh "tgrep --version"

                                log.info("Generating tgrep trigram index...")
                                if (config?.excludePatterns) {
                                    // Convert list into -e flags: "-e 'archive/**' -e '.wiki/**' -e 'raw/**' -e 'private/**'"
                                    String excludeFlags = config.excludePatterns.collect { "-e ${it.inspect()}" }.join(' ')

                                    log.info("Generating tgrep trigram index...")
                                    sh "tgrep index ${excludeFlags} --index-path ${config.indexDir}/tgrep.idx ."
                                } else {
                                    sh "tgrep index --index-path ${config.indexDir}/tgrep.idx ."
                                }
                            }
                        }
                    }

                    stage('Indexer: Build SQLite FTS5 Index') {
                        steps {
                            script {
                                log.info("Generating SQLite FTS5 full-text search index...")
                                sh "build-fts5-index --config .fts5-indexer.yml"
                            }
                        }
                    }

                    stage('Indexer: Archive & Publish Release Asset') {
                        steps {
                            script {
                                publishGiteaReleaseAsset(
                                    sourceDir: config.indexDir,
                                    archiveName: "code_index.tar.gz",
                                    giteaHost: config.giteaHost,
                                    releaseTagName: config.releaseTagName,
                                    credentialsId: config.gitCredentialsId,
                                    body: 'Latest code indexes generated by the run-indexer pipeline.'
                                )

                                config.gitRemoteBuildStatus = "SUCCESSFUL"
                                currentBuild.result = "SUCCESS"
                            }
                        }
                    }
                }
            }
        }
        post {
            always {
                script {
                    config.gitRemoteBuildStatus = "COMPLETED"
                    notifyGitRemoteRepo(
                        config.gitRemoteRepoType,
                        gitRemoteBuildKey: config.gitRemoteBuildKey,
                        gitRemoteBuildName: config.gitRemoteBuildName,
                        gitRemoteBuildStatus: config.gitRemoteBuildStatus,
                        gitRemoteBuildSummary: config.gitRemoteBuildSummary,
                        gitCommitId: config.gitCommitId
                    )

                    try {
                        cleanWs()
                    } catch (Exception ex) {
                        log.warn("Unable to cleanup workspace: ", ex.getMessage())
                    }
                }
            }
        }
    }
}

//@NonCPS
Map loadPipelineConfig(Map params) {
    Map config = [:]

    params.each { key, value ->
        key = Utilities.decapitalize(key)
        if (value != "") config[key] = value
    }

    config.get('logLevel', "INFO")
    log.setLevel(config.logLevel)

    // Defaults
    config.get('jenkinsNodeLabel', 'docker')
    config.get('timeout', 1)
    config.get('timeoutUnit', 'HOURS')
    config.get('skipDefaultCheckout', false)
    config.get('indexDir', '.code_index')
//     config.get('ignoreFile', '.gitignore')
    config.get('ignoreFile', '.gitignore.pub')
    config.get("runnerImage", "media.johnson.int:5000/jenkins-docker-agent:latest")

    List runnerArgsList = []
    if (config?.runnerUid && config?.runnerGid) {
        runnerArgsList.push("-u ${config.runnerUid}:${config.runnerGid}")
    } else {
        runnerArgsList.push("-u root:root")
        runnerArgsList.push("--privileged")
    }
    runnerArgsList.push("--network host")
    runnerArgsList.push("-e SSH_AUTH_SOCK")
    runnerArgsList.push("-v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro")

    config.get("runnerArgs", runnerArgsList.join(" "))

    config.get('releaseTagName', 'code-index')
    config.get('gitCredentialsId', 'infra-jenkins-git-user')
    config.get('gitRemoteRepoType', 'gitea')

    config.gitRemoteBuildStatus = "INPROGRESS"
    config.get("gitRemoteBuildKey", 'run-indexer')
    config.get("gitRemoteBuildName", 'Run Indexers')
    config.get("gitRemoteBuildSummary", "${config.gitRemoteBuildName} update")

    config.gitCommitId = env.GIT_COMMIT

    // Parameter definition in your helper/step script
    List<String> excludePatternsDefault = [
        'archive/**',
        '.wiki/**',
        'raw/**',
        'private/**',
        '.code_index/**'
    ]
    config.get("excludePatterns", excludePatternsDefault)

    return config
}
